### ISSUE TITLE
Crash when selecting specific mod

### ISSUE THREAD

**Issue by x7airworker** [Artentus/ModMyFactory#114]
If i select the "Computer Core" Mod in the downloads section, the Application crashes. Probably because of the description.
<b>Crash log:</b>
 

> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ModMyFactory.Controls.FormattingTextBlock.FormatText(String text, ICollection`1 inlines, Int32& index, String[] endPatterns)
   at ModMyFactory.Controls.FormattingTextBlock.FormatText(String text, ICollection`1 inlines, Int32& index, String[] endPatterns)
   at ModMyFactory.Controls.FormattingTextBlock.AddTextToTextBlockFormatted(TextBlock textBlock, String text)
   at ModMyFactory.Controls.FormattingTextBlock.ApplyTextFormatted()
   at ModMyFactory.Controls.FormattingTextBlock.OnTextPropertyChanged(DependencyObject source, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.ClrBindingWorker.NewValueAvailable(Boolean dependencySourcesChanged, Boolean initialValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.ClrBindingWorker.OnSourcePropertyChanged(Object o, String propName)
   at System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   at System.ComponentModel.PropertyChangedEventManager.OnPropertyChanged(Object sender, PropertyChangedEventArgs args)
   at ModMyFactory.ViewModels.OnlineModsViewModel.set_SelectedModDescription(String value)
   at ModMyFactory.ViewModels.OnlineModsViewModel.set_ExtendedInfo(ExtendedModInfo value)
   at ModMyFactory.ViewModels.OnlineModsViewModel.<LoadExtendedModInfoAsync>d__129.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ModMyFactory.ViewModels.OnlineModsViewModel.<<set_SelectedMod>b__69_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Artentus** [comment]
I've identified the issue and solved it.

However at the moment I don't know when I'll be able to release a new version, I'm busy again with uni.
