### ISSUE TITLE
The 'Open folder' buttons will crash the application if the folder directories are not set.

### ISSUE THREAD

**Issue by tzwaan** [Artentus/ModMyFactory#13]

**Comment by Artentus** [comment]
If the application crashed a crash log should have been created in %AppData%\ModMyFactory. Please post this log here, it may help me resolve this bug.

**Comment by tzwaan** [comment]
This is the latest crash log I got. It's not exactly the same crash as I described (this happened during the linking of the steam folder), but I suspect it has the same cause. After adding the steam folder (it crashing) and restarting, both problems had fixed itself.

System.IO.DirectoryNotFoundException: Could not find a part of the path.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.MoveTo(String destFileName)
   at ModMyFactory.ViewModels.VersionManagementViewModel.<>c__DisplayClass43_0.<MoveContentsToPreserveAsync>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ModMyFactory.ViewModels.VersionManagementViewModel.<MoveContentsToPreserveAsync>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ModMyFactory.ViewModels.VersionManagementViewModel.<SelectSteamVersion>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ModMyFactory.ViewModels.VersionManagementViewModel.<<-ctor>b__37_4>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Artentus** [comment]
Thanks.
So this chrash log is a different bug from what you wrote in the title (I have already fixed that one). Seems I just forgot to create the folders if they don't exist, this will be a pretty quick fix.

**Comment by tzwaan** [comment]
Yeah I suspected it would be something like that.

**Comment by benlipp** [comment]
I also have this issue when selecting my Steam installation

**Comment by Artentus** [comment]
Should be fixed in version 1.2.1.
