### ISSUE TITLE
Crash on Update Mods

### ISSUE THREAD

**Issue by benlipp** [Artentus/ModMyFactory#17]
I'm running version 1.2.1. I clicked the update mods icon, it got through a few of them, and crashed. Here's my crash log:

`System.NullReferenceException: Object reference not set to an instance of an object.
   at ModMyFactory.ViewModels.MainViewModel.<GetModUpdatesAsync>d__134.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ModMyFactory.ViewModels.MainViewModel.<UpdateMods>d__137.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ModMyFactory.ViewModels.MainViewModel.<<-ctor>b__113_13>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
`

**Comment by Artentus** [comment]
Can you remember which mod caused the crash?
I have used the updater many times myself and never gotten this error before.

**Comment by Artentus** [comment]
Please check if version 1.2.2 fixed this issue for you.

**Comment by Artentus** [comment]
As you have not answered since, can I assume this to be fixed? I would like to close this issue if it has been resolved.

**Comment by benlipp** [comment]
Yeah, sorry! Fixed. Closed #17

On Sat, Nov 5, 2016, 9:17 AM Mathis Rech notifications@github.com wrote:

As you have not answered since, can I assume this to be fixed? I would like
to close this issue if it has been resolved.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/Artentus/ModMyFactory/issues/17#issuecomment-258610854,
or mute the thread
