### ISSUE TITLE
"Getting Started" Wiki page is blank

### ISSUE THREAD

**Issue by AlphaJuliettOmega** [Artentus/ModMyFactory#29]
What do I need to install to run the .cs files?
Mono?

Do I need to compile this repo to be able to use the mod manager?

Great work, I hope I can figure out how to use it :)

**Comment by Artentus** [comment]
I know the page is blank, the Wiki is WIP at the moment. ;)
I will continue working on it once I have finished the actual application.

To run this you can just download the newest release (not the source) and extract it to a folder of your choice, it's all set up and ready to go.

**Comment by AlphaJuliettOmega** [comment]
Trying to run App.xaml gives me this exception:
(after passing one exception by allowing Xaml pages in my browser)
Startup URI: C:\Users\AJ\AppData\Local\Temp\Temp1_ModMyFactory-master.zip\ModMyFactory-master\ModMyFactory\ModMyFactory\App.xaml
Application Identity: 

System.Windows.Markup.XamlParseException: 'The invocation of the constructor on type 'System.Windows.Application' that matches the specified binding constraints threw an exception.' Line number '1' and line position '14'.
---> System.InvalidOperationException: Cannot create more than one System.Windows.Application instance in the same AppDomain.
   at System.Windows.Application..ctor()
   at System.Windows.Baml2006.WpfSharedBamlSchemaContext.<>c.<Create_BamlType_Application>b__408_0()
   at System.Windows.Baml2006.WpfKnownTypeInvoker.CreateInstance(Object[] arguments)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstanceWithCtor(XamlType xamlType, Object[] args)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstance(XamlType xamlType, Object[] args)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.LoadAsync(XmlReader reader, ParserContext parserContext)
   at System.Windows.Markup.XamlReader.LoadAsync(Stream stream, ParserContext parserContext)
   at MS.Internal.AppModel.AppModelKnownContentFactory.XamlConverter(Stream stream, Uri baseUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader& asyncObjectConverter)
   at MS.Internal.AppModel.MimeObjectFactory.GetObjectAndCloseStream(Stream s, ContentType contentType, Uri baseUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader& asyncObjectConverter)
   at System.Windows.Navigation.NavigationService.GetObjectFromResponse(WebRequest request, WebResponse response, Uri destinationUri, Object navState)
   at System.Windows.Navigation.NavigationService.HandleWebResponse(IAsyncResult ar)
   at System.Windows.Navigation.NavigationService.<>c__DisplayClass106_0.<HandleWebResponseOnRightDispatcher>b__0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.StartDispatcherInBrowser(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

---

PresentationHost.exe v10.0.10586.0 (th2_release.151029-1700) - C:\Windows\SysWOW64\PresentationHost.exe
ntdll.dll v10.0.10586.0 (th2_release.151029-1700) - C:\Windows\SYSTEM32\ntdll.dll
KERNEL32.DLL v10.0.10586.0 (th2_release.151029-1700) - C:\Windows\SYSTEM32\KERNEL32.DLL
KERNELBASE.dll v10.0.10586.0 (th2_release.151029-1700) - C:\Windows\SYSTEM32\KERNELBASE.dll
avcuf32.dll v3.12.15976.6498 - C:\Program Files\N-able Technologies\AVDefender\Signatures\AVC\AVC3_00558_013\avcuf32.dll
ADVAPI32.dll v10.0.10586.0 (th2_release.151029-1700) - C:\Windows\SYSTEM32\ADVAPI32.dll
msvcrt.dll v7.0.10586.0 (th2_release.151029-1700) - C:\Windows\SYSTEM32\msvcrt.dll
sechost.dll v10.0.10586.0 (th2_release.151029-1700) - C:\Windows\SYSTEM32\sechost.dll
RPCRT4.dll v10.0.10586.0 (th2_release.151029-1700) - C:\Windows\SYSTEM32\RPCRT4.dll
SspiCli.dll v10.0.10586.0 (th2_release.151029-1700) - C:\Windows\SYSTEM32\SspiCli.dll
CRYPTBASE.dll v10.0.10586.0 (th2_release.151029-1700) - C:\Windows\SYSTEM32\CRYPTBASE.dll
bcryptPrimitives.dll v10.0.10586.0 (th2_release.151029-1700) - C:\Windows\SYSTEM32\bcryptPrimitives.dll
USER32.dll v10.0.10586.0 (th2_release.151029-1700) - C:\Windows\SYSTEM32\USER32.dll
GDI32.dll v10.0.10586.63 (th2_release.160104-1513) - C:\Windows\SYSTEM32\GDI32.dll
ole32.dll v10.0.10586.0 (th2_release.151029-1700) - C:\Windows\SYSTEM32\ole32.dll
combase.dll v10.0.10586.0 (th2_release.151029-1700) - C:\Windows\SYSTEM32\combase.dll
OLEAUT32.dll v10.0.10586.0 - C:\Windows\SYSTEM32\OLEAUT32.dll
SHLWAPI.dll v10.0.10586.0 (th2_release.151029-1700) - C:\Windows\SYSTEM32\SHLWAPI.dll
SHELL32.dll v10.0.10586.103 (th2_release.160126-1819) - C:\Windows\SYSTEM32\SHELL32.dll
cfgmgr32.dll v10.0.10586.0 (th2_release.151029-1700) - C:\Windows\SYSTEM32\cfgmgr32.dll
windows.storage.dll v10.0.10586.0 (th2_release.151029-1700) - C:\Windows\SYSTEM32\windows.storage.dll
kernel.appcore.dll v10.0.10586.0 (th2_release.151029-1700) - C:\Windows\SYSTEM32\kernel.appcore.dll
shcore.dll v10.0.10586.0 (th2_release.151029-1700) - C:\Windows\SYSTEM32\shcore.dll
powrprof.dll v10.0.10586.0 (th2_release.151029-1700) - C:\Windows\SYSTEM32\powrprof.dll
profapi.dll v10.0.10586.0 (th2_release.151029-1700) - C:\Windows\SYSTEM32\profapi.dll
mscoree.dll v10.0.10586.0 (th2_release.151029-1700) - C:\Windows\SYSTEM32\mscoree.dll
WININET.dll v11.00.10586.0 (th2_release.151029-1700) - C:\Windows\SYSTEM32\WININET.dll
urlmon.dll v11.00.10586.0 (th2_release.151029-1700) - C:\Windows\SYSTEM32\urlmon.dll
iertutil.dll v11.00.10586.0 (th2_release.151029-1700) - C:\Windows\SYSTEM32\iertutil.dll
IMM32.DLL v10.0.10586.0 (th2_release.151029-1700) - C:\Windows\SYSTEM32\IMM32.DLL
PresentationHost_v0400.dll v4.6.1038.0 built by: NETFXREL2 - C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\PresentationHost_v0400.dll
PSAPI.DLL v10.0.10586.0 (th2_release.151029-1700) - C:\Windows\SYSTEM32\PSAPI.DLL
MSVCR120_CLR0400.dll v12.00.52512.0 built by: VSWINSERVICING - C:\Windows\SYSTEM32\MSVCR120_CLR0400.dll
VERSION.dll v10.0.10586.0 (th2_release.151029-1700) - C:\Windows\SYSTEM32\VERSION.dll
uxtheme.dll v10.0.10586.0 (th2_release.151029-1700) - C:\Windows\system32\uxtheme.dll
clbcatq.dll v2001.12.10941.16384 (th2_release.151029-1700) - C:\Windows\SYSTEM32\clbcatq.dll
ieproxy.dll v11.00.10586.212 (th2_release_sec.160328-1908) - C:\Windows\SYSTEM32\ieproxy.dll
PROPSYS.dll v7.00.10586.0 (th2_release.151029-1700) - C:\Windows\SYSTEM32\PROPSYS.dll
ActXPrxy.dll v10.0.10586.218 (th2_release.160401-1800) - C:\Windows\SYSTEM32\ActXPrxy.dll
sxs.dll v10.0.10586.0 (th2_release.151029-1700) - C:\Windows\SYSTEM32\sxs.dll
PresentationHostProxy.dll v10.0.10586.0 (th2_release.151029-1700) - C:\Windows\SYSTEM32\PresentationHostProxy.dll
MSCTF.dll v10.0.10586.0 (th2_release.151029-1700) - C:\Windows\SYSTEM32\MSCTF.dll
dwmapi.dll v10.0.10586.0 (th2_release.151029-1700) - C:\Windows\system32\dwmapi.dll
mscoreei.dll v4.6.1038.0 built by: NETFXREL2 - C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscoreei.dll
clr.dll v4.6.1078.0 built by: NETFXREL3STAGE - C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
mscorlib.ni.dll v4.6.1078.0 built by: NETFXREL3STAGE - C:\Windows\assembly\NativeImages_v4.0.30319_32\mscorlib\599e1e123d8890a906c66fa63ba868bd\mscorlib.ni.dll
System.ni.dll v4.6.1075.0 built by: NETFXREL3STAGE - C:\Windows\assembly\NativeImages_v4.0.30319_32\System\53659adf088ea34465ba7148e260c847\System.ni.dll
System.Core.ni.dll v4.6.1038.0 built by: NETFXREL2 - C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Core\13a04e6416bbbaaca12da6cbcad76c68\System.Core.ni.dll
WindowsBase.ni.dll v4.6.1073.0 built by: NETFXREL3STAGE - C:\Windows\assembly\NativeImages_v4.0.30319_32\WindowsBase\c98bae6a53cf6b2bc173eb3db974af06\WindowsBase.ni.dll
CRYPTSP.dll v10.0.10586.0 (th2_release.151029-1700) - C:\Windows\SYSTEM32\CRYPTSP.dll
rsaenh.dll v10.0.10586.0 (th2_release.151029-1700) - C:\Windows\system32\rsaenh.dll
bcrypt.dll v10.0.10586.0 (th2_release.151029-1700) - C:\Windows\SYSTEM32\bcrypt.dll
PresentationCore.ni.dll v4.6.1073.0 built by: NETFXREL3STAGE - C:\Windows\assembly\NativeImages_v4.0.30319_32\PresentationCore\f23d9459e7fdce36221187ea675fc624\PresentationCore.ni.dll
PresentationFramework.ni.dll v4.6.1073.0 - C:\Windows\assembly\NativeImages_v4.0.30319_32\Presentatio5ae0f00f#\6562ef16de0b9951d9ee834026fdc7a5\PresentationFramework.ni.dll
dwrite.dll v10.0.10586.0 (th2_release.151029-1700) - C:\Windows\SYSTEM32\dwrite.dll
wpfgfx_v0400.dll v4.6.1073.0 built by: NETFXREL3STAGE - C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\wpfgfx_v0400.dll
PresentationNative_v0400.dll v4.6.1038.0 built by: NETFXREL2 - C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\PresentationNative_v0400.dll
System.Xaml.ni.dll v4.6.1073.0 built by: NETFXREL3STAGE - C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Xaml\da69f2d0cab254ee15b8fbf55286111d\System.Xaml.ni.dll
clrjit.dll v4.6.1078.0 built by: NETFXREL3STAGE - C:\Windows\Microsoft.NET\Framework\v4.0.30319\clrjit.dll
System.Drawing.ni.dll v4.6.1078.0 built by: NETFXREL3STAGE - C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Drawing\562e673887ea3a14ccbe0cb911ff32df\System.Drawing.ni.dll
PresentationFramework.Aero2.ni.dll v4.6.1038.0 built by: NETFXREL2 - C:\Windows\assembly\NativeImages_v4.0.30319_32\Presentatioaec034ca#\52355744b3fdfdca37ba808ceff7beee\PresentationFramework.Aero2.ni.dll
System.Configuration.ni.dll v4.6.1038.0 built by: NETFXREL2 - C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Configuration\206e48e6105b08574bb8e821ef9a6b4a\System.Configuration.ni.dll
System.Xml.ni.dll v4.6.1064.2 built by: NETFXREL3STAGE - C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Xml\21709e6e2d2b139a920a46d9caa86473\System.Xml.ni.dll
WtsApi32.dll v10.0.10586.0 (th2_release.151029-1700) - C:\Windows\SYSTEM32\WtsApi32.dll
WINSTA.dll v10.0.10586.0 (th2_release.151029-1700) - C:\Windows\SYSTEM32\WINSTA.dll
d3d9.dll v10.0.10586.0 (th2_release.151029-1700) - C:\Windows\SYSTEM32\d3d9.dll
igdumdim32.dll v20.19.15.4331 - C:\Windows\SYSTEM32\igdumdim32.dll
SETUPAPI.dll v10.0.10586.0 (th2_release.151029-1700) - C:\Windows\SYSTEM32\SETUPAPI.dll
igdusc32.dll v20.19.15.4331 - C:\Windows\SYSTEM32\igdusc32.dll
msctfui.dll v10.0.10586.0 (th2_release.151029-1700) - C:\Windows\system32\msctfui.dll
UIAutomationTypes.ni.dll v4.6.1038.0 built by: NETFXREL2 - C:\Windows\assembly\NativeImages_v4.0.30319_32\UIAutomationTypes\78b15a8cabb9a9de331bb311814b79ea\UIAutomationTypes.ni.dll
UIAutomationCore.dll v7.2.10586.0 (th2_release.151029-1700) - C:\Windows\SYSTEM32\UIAutomationCore.dll
USERENV.dll v10.0.10586.0 (th2_release.151029-1700) - C:\Windows\SYSTEM32\USERENV.dll
diasymreader.dll v14.00.1038.0 built by: NETFXREL2 - C:\Windows\Microsoft.NET\Framework\v4.0.30319\diasymreader.dll

Thank you for the reply <3

**Comment by Artentus** [comment]
How can you run App.xaml? That is not an executable file.

You just have to run ModMyFactory.exe from the ZIP archive.

**Comment by AlphaJuliettOmega** [comment]
App.xaml can open in Internet Explorer,
Please apologize my ignorance if it's obvious but where do I find the ModMyFactory.exe file?
It's not included if I download this repository!

**Comment by Artentus** [comment]
Don't download the repository, download the newest release from the releases section:
https://github.com/Artentus/ModMyFactory/releases

**Comment by AlphaJuliettOmega** [comment]
I'm at a loss for words :')
Thank you

**Comment by Artentus** [comment]
Glad I could help.
