### ISSUE TITLE
Crash when putting in incorrect credentials

### ISSUE THREAD

**Issue by benlipp** [Artentus/ModMyFactory#36]
Pretty self-explanatory
```
System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.HttpWebRequest.GetResponse()
   at ModMyFactory.Web.WebHelper.GetDocument(String url, CookieContainer container, Byte[] content)
   at ModMyFactory.Web.ApiAuthentication.LogIn(String username, SecureString password, String& token)
   at ModMyFactory.GlobalCredentials.LogIn(Window owner, String& loginToken)
   at ModMyFactory.ViewModels.OnlineModsViewModel.<DownloadSelectedModRelease>d__56.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ModMyFactory.ViewModels.OnlineModsViewModel.<<-ctor>b__55_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by Artentus** [comment]
Fixed for version 1.4.3.
