### ISSUE TITLE
Toomb Stones not recognized as valid mod

### ISSUE THREAD

**Issue by Alxandr** [Artentus/ModMyFactory#39]
When I try to add toomb stones form the zip I get "this is not a valid mod", and when I try to download it from within the program I get the following exception:

```
System.InvalidOperationException: The server sent an invalid mod file.
   at ModMyFactory.Web.ModWebsite.<DownloadReleaseAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ModMyFactory.ViewModels.OnlineModsViewModel.<DownloadSelectedModRelease>d__60.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at ModMyFactory.ViewModels.OnlineModsViewModel.<DownloadSelectedModRelease>d__60.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ModMyFactory.ViewModels.OnlineModsViewModel.<<-ctor>b__58_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by Artentus** [comment]
I know about this, but the error here is on the side of the creator of Tomb Stones, not me. The info.json file inside the mod archive contains an entry twice.

**Comment by Artentus** [comment]
Starting from version 1.5 ModMyFactory will accept Tomb Stones (and all other mods that have duplicate entries in their info.json file) as valid.

Mod authors should still not do this of course.

**Comment by Alxandr** [comment]
I agree, but the fact that the game handles it means you probably should too :)
