### ISSUE TITLE
Crash on load when there's .15 mods in the .14 mod folder

### ISSUE THREAD

**Issue by tzwaan** [Artentus/ModMyFactory#48]
When .15 just released I used the ingame update function to update some mods. Now modmyfactory crashes on startup due to .15 mods being in the .14 mod folder.
I would assume the expected behaviour would be to either fix it by moving the conflicting mods to the other folder, or to ignore them altogether and launch without them.

``` 
System.Windows.Markup.XamlParseException: Provide value on 'System.Windows.Markup.StaticExtension' threw an exception. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: The mod angelsaddons-oresilos_0.3.0.zip is targeting Factorio version 0.15 but resides in directory 0.14.
   at ModMyFactory.Models.Mod.CreateModDictionary(ICollection`1 parentCollection, ICollection`1 modpackCollection)
   at ModMyFactory.ViewModels.MainViewModel.LoadModsAndModpacks()
   at ModMyFactory.ViewModels.MainViewModel..ctor()
   at ModMyFactory.ViewModels.MainViewModel.get_Instance()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Windows.Markup.StaticExtension.GetFieldOrPropertyValue(Type type, String name, Object& value)
   at System.Windows.Markup.StaticExtension.ProvideValue(IServiceProvider serviceProvider)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)```

**Comment by Artentus** [comment]
This is the intended behaviour as this should never happen. The only way this can happen is if you either place the mods wrong manually or if you update Factorio through the ingame updater, which will currupt the configuration anyway.
