### ISSUE TITLE
Crash when mod updated outside of program between versions

### ISSUE THREAD

**Issue by JoshCrook** [Artentus/ModMyFactory#51]
Crash log:
```
System.Windows.Markup.XamlParseException: Provide value on 'System.Windows.Markup.StaticExtension' threw an exception. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: The mod AddAssemblerBatteries_0.15.1.zip is targeting Factorio version 0.15 but resides in directory 0.14.
   at ModMyFactory.Models.Mod.CreateModDictionary(ICollection`1 parentCollection, ICollection`1 modpackCollection)
   at ModMyFactory.ViewModels.MainViewModel.LoadModsAndModpacks()
   at ModMyFactory.ViewModels.MainViewModel..ctor()
   at ModMyFactory.ViewModels.MainViewModel.get_Instance()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Windows.Markup.StaticExtension.GetFieldOrPropertyValue(Type type, String name, Object& value)
   at System.Windows.Markup.StaticExtension.ProvideValue(IServiceProvider serviceProvider)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
I tried to resolve this by moving my mods and saves to the Factorio appdata folder and wiping out my MMF appdata folder, and then reconfiguring it. After re-adding steam version, it crashed with the same error.

I deleted the specific mod and it resolved the issue.

**Comment by Artentus** [comment]
This is actually intended behaviour because this state is invalid. If you manually edit the mod files that are managed by ModMyFactory you have to know what you are doing and I do not take responsibility if you corrupt the configuration.

ModMyFactory uses a separate folder for every main version of Factorio to store mods in. If you update a 0.14 mod manually to 0.15 you have to put the updated mod into the 0.15 folder, not into the 0.14 folder.

**Comment by JoshCrook** [comment]
I didn't update it manually, I updated it from within Factorio, which caused the original error.

Wiping out MMF and reinstalling it still stuck that mod in the wrong folder, it wasn't anything I did that put it there.

**Comment by Artentus** [comment]
Factorio does not update to incopatible mod version though, so you must have updated Factorio beforhand, right?

**Comment by JoshCrook** [comment]
Yes

**Comment by Artentus** [comment]
Did you use ModMyFactory to update Factorio? THe ingame auto-updater is not supported and will break things.
