### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by szentigrad3** [Artentus/ModMyFactory#63]
System.IO.InvalidDataException: End of Central Directory record could not be found.
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at ModMyFactory.Models.Mod.ArchiveFileValid(FileInfo archiveFile, Version& validFactorioVersion, String& validName, Version& validVersion)
   at ModMyFactory.Models.Mod.CreateModDictionary(ICollection`1 parentCollection, ICollection`1 modpackCollection)
   at ModMyFactory.ViewModels.MainViewModel.LoadModsAndModpacks()
   at ModMyFactory.ViewModels.MainViewModel.<ApplySettings>d__221.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ModMyFactory.ViewModels.MainViewModel.<OpenSettings>d__222.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ModMyFactory.ViewModels.MainViewModel.<<-ctor>b__189_7>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Artentus** [comment]
Looks like one of your mods is corrupt.

**Comment by Dimava** [comment]
Corrupted mod should be listed in logfile at least

**Comment by Artentus** [comment]
I'll look into that.

**Comment by Artentus** [comment]
As of 1.5.12 ModMyFactory will no longer crash when encountering a corrupted mod archive but instead ignore it and write an error message into the log.
