### ISSUE TITLE
Crash when updating mods.

### ISSUE THREAD

**Issue by credomane** [Artentus/ModMyFactory#74]
OK. After flip flopping back-n-forth. This does affect all mods but at complete random. Some times updates will go through successfully without issue. Other times they crash with the below error. Most of the time the crash happens, though.

Just a matter of updating all mods to trigger the crash.

    System.InvalidOperationException: Failed to compare two elements in the array. ---> System.NullReferenceException: Object reference not set to an instance of an object.
       at ModMyFactory.MVVM.Sorters.ModSorter.Compare(Mod x, Mod y)
       at System.Array.BinarySearch(Array array, Int32 index, Int32 length, Object value, IComparer comparer)
       --- End of inner exception stack trace ---
       at System.Array.BinarySearch(Array array, Int32 index, Int32 length, Object value, IComparer comparer)
       at System.Windows.Data.ListCollectionView.AdjustBefore(NotifyCollectionChangedAction action, Object item, Int32 index)
       at System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
       at System.Collections.Specialized.NotifyCollectionChangedEventHandler.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
       at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
       at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
       at ModMyFactory.ViewModels.MainViewModel.<UpdateModAsyncInner>d__210.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at ModMyFactory.ViewModels.MainViewModel.<UpdateModsAsyncInner>d__211.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at ModMyFactory.ViewModels.MainViewModel.<UpdateMods>d__212.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at ModMyFactory.ViewModels.MainViewModel.<<-ctor>b__189_6>d.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by credomane** [comment]
And closing this....was debugging the 0.5.11.0 release. Crash happens every time. I then updated my fork to the latest commits and it started working fine.

Just now realised I did this. Checked commit history and found that you had already fixed this exactly because of the Mod portal API changes.

\*hangs head in shame for not noticing 0.5.11.0 tag != master anymore\*
