### ISSUE TITLE
MMF crashing on mod downloads

### ISSUE THREAD

**Issue by PowerOnly** [Artentus/ModMyFactory#84]
Just downloaded and attempted install on a new laptop (my former laptop MMF worked flawlessly after following install instructions).

The issue is MMF crashes on downloading any mod and reports a "log has been created."  The crash log it reports is as follows:

+++
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Prince of Zzyzx\AppData\Roaming\Factorio\mods'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   at ModMyFactory.ViewModels.VersionManagementViewModel.PreserveMods(DirectoryInfo localModDirectory, Boolean move)
   at ModMyFactory.ViewModels.VersionManagementViewModel.<>c__DisplayClass48_0.<PreserveContentsAsync>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ModMyFactory.ViewModels.VersionManagementViewModel.<PreserveContentsAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ModMyFactory.ViewModels.VersionManagementViewModel.<SelectSteamVersion>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ModMyFactory.ViewModels.VersionManagementViewModel.<<-ctor>b__39_4>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
+++

Question is what have I done wrong or how do i get this corrected?

**Comment by Artentus** [comment]
You get this when downloading mods? That is very peculiar, because from the log it looks like you were doing something in the Factorio Version Manager.

Also, the path that is referred to belongs to either the Factorio Steam version or the Factorio automatic installer version. The only time MMF searches for that path is when you are trying to add one of these versions inside the Version manager.

That being said I don't know what to make of this now. Maybe you pasted a different crash log?

**Comment by PowerOnly** [comment]
Maybe so.  I'll definitely check and make sure.  I'll try again to be certain.

**Comment by PowerOnly** [comment]
Ok.  I tried another download just a bit ago.  Marked the time and confirmed the crash log file date and time was spot on.  The resulting crash log file contained the following:

+++
System.InvalidOperationException: The server sent an invalid mod file.
   at ModMyFactory.Web.ModWebsite.<DownloadReleaseAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ModMyFactory.ViewModels.OnlineModsViewModel.<DownloadSelectedModRelease>d__87.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at ModMyFactory.ViewModels.OnlineModsViewModel.<DownloadSelectedModRelease>d__87.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ModMyFactory.ViewModels.OnlineModsViewModel.<<-ctor>b__85_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
+++

Hopefully this helps.  And this is confusing to me because I installed MMF on my Lenovo quite a while ago and it worked perfectly.  When I purchased this MSI I figured it would go equally as smoothly.  We'll get it eventually, though.

**Comment by Xetaxheb** [comment]
Getting this too

**Comment by Artentus** [comment]
Ok so this log looks a lot more promising, thanks.

It appears MMF was not happy with the downloaded mod file for one reason or another. If you tell me which mod you tried to download I can take a look at it on my machine.

**Comment by PowerOnly** [comment]
It does this on every mod.  I tested it with Arborium, Angels Infinite Ores and several others.

**Comment by PowerOnly** [comment]
Artentus, I started messing around with MMF a bit more yesterday.  I uninstalled 1.15.11 and tested the individual 1.15.12preX releases.  With 1.15.12pre3 it finally worked.  I am now able to download mods with no crashes.  Game on!

Also thanks both for the Mod My Factory tool and for your help in getting it up and running on this new machine.

**Comment by Artentus** [comment]
Oh you were still on 1.5.11? That explains a lot, that version is completely non-functional in multiple ways. I was tasting the lastest code and couldn't find anything.

The pre-releases fix all the breaking bugs but I haven't released a stable yet because not all functionality is working yet. With the mod portal update the API underwent some changes and not everything I used even exists anymore. I have asked the devs about this a while back but so far have not received an answer.

**Comment by Xetaxheb** [comment]
Same, issue is 1.5.11, might want to edit the release info to "NON-FUNCTIONAL" or set a new 'latest' because https://github.com/Artentus/ModMyFactory/releases/latest takes you to that one

**Comment by Artentus** [comment]
I have left a note on 1.5.11 to redirect to the latest pre-release.

Pre-releases cannot be marked as latest as that feature is just provided through GitHub automatically.
