### ISSUE TITLE
crash when updating mods

### ISSUE THREAD

**Issue by szentigrad3** [Artentus/ModMyFactory#88]
System.NullReferenceException: Object reference not set to an instance of an object.
   at ModMyFactory.GlobalCredentials.LogIn(Window owner, String& loginToken)
   at ModMyFactory.ViewModels.MainViewModel.<UpdateMods>d__215.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ModMyFactory.ViewModels.MainViewModel.<<-ctor>b__189_6>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Artentus** [comment]
Make sure you are running the latest version and then clear and reenter your credentials.
